/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author Marco
 */
public class GUIChess extends javax.swing.JFrame {

    /**
     * Creates new form GUIChess
     */
    public GUIChess() {
        initComponents();
        overlay.setBackground(new Color(0,0,0,200));
        helpPage.setVisible(false);
        gameBoard.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JTabbedPane();
        startingPage = new javax.swing.JPanel();
        player2 = new javax.swing.JTextField();
        player1 = new javax.swing.JTextField();
        start = new javax.swing.JButton();
        help = new javax.swing.JToggleButton();
        exit = new javax.swing.JButton();
        player1Label = new javax.swing.JLabel();
        player2Label = new javax.swing.JLabel();
        playerScores = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        playerBlack = new javax.swing.JLabel();
        playerWhite = new javax.swing.JLabel();
        turnLabel = new javax.swing.JLabel();
        helpPage = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        gameBoard = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        overlay = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PDC CHESS PROJECT");
        setMinimumSize(new java.awt.Dimension(720, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(720, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startingPage.setBackground(new java.awt.Color(46, 46, 46));
        startingPage.setBorder(new javax.swing.border.SoftBevelBorder(0));
        startingPage.setForeground(new java.awt.Color(153, 153, 153));
        startingPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        player2.setBackground(new java.awt.Color(153, 153, 153));
        player2.setText("player2");
        player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2ActionPerformed(evt);
            }
        });
        startingPage.add(player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 180, 30));

        player1.setBackground(new java.awt.Color(153, 153, 153));
        player1.setText("player1");
        player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1ActionPerformed(evt);
            }
        });
        startingPage.add(player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 180, 30));

        start.setBackground(new java.awt.Color(0, 102, 102));
        start.setText("Start New Game");
        start.setFocusPainted(false);
        start.setFocusable(false);
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPerformed(evt);
            }
        });
        startingPage.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 130, 30));

        help.setText("Help");
        help.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                helpIsSelected(evt);
            }
        });
        startingPage.add(help, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, 20));

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        startingPage.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 80, 20));

        player1Label.setBackground(new java.awt.Color(255, 255, 255));
        player1Label.setForeground(new java.awt.Color(255, 255, 255));
        player1Label.setText("Enter Player 1 Name (BLACK) :");
        startingPage.add(player1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        player2Label.setBackground(new java.awt.Color(255, 255, 255));
        player2Label.setForeground(new java.awt.Color(255, 255, 255));
        player2Label.setText("Enter Player 2 Name (WHITE) :");
        startingPage.add(player2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        sidePanel.addTab("Menu", startingPage);

        jProgressBar1.setStringPainted(true);

        jProgressBar2.setStringPainted(true);

        playerBlack.setText("Player One:");

        playerWhite.setText("Player Two:");

        turnLabel.setText("....Black Makes the first move....");

        javax.swing.GroupLayout playerScoresLayout = new javax.swing.GroupLayout(playerScores);
        playerScores.setLayout(playerScoresLayout);
        playerScoresLayout.setHorizontalGroup(
            playerScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playerScoresLayout.createSequentialGroup()
                .addGroup(playerScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, playerScoresLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(playerScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(playerScoresLayout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addComponent(turnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, playerScoresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(playerScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerWhite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(playerBlack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        playerScoresLayout.setVerticalGroup(
            playerScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerScoresLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(turnLabel)
                .addGap(29, 29, 29)
                .addComponent(playerBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(playerWhite, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        sidePanel.addTab("Current Game", playerScores);

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 240, 480));
        sidePanel.getAccessibleContext().setAccessibleName("Menu");
        sidePanel.getAccessibleContext().setAccessibleDescription("");

        helpPage.setEnabled(false);
        helpPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<html>HELP <br/><br/> This is a simple game of chess, the Board Array consists of 8 x 8 tiles, with the y axis starting at 0 and x axis determined by characters. <br/> A player wins by capturing the enemy team's King. <br/><br/>             • Pawns are unusual because they move and capture in different ways: they move forward, but capture diagonally. Pawns can only move forward one square at a time<br/> • The bishop may move as far as it wants, but only diagonally.<br/> • Knights move in a very different way from the other pieces – going two squares in one direction, and then one more move at a 90 degree angle, just like the shape of an 'L'<br/> • The rook may move as far as it wants, but only forward, backward, and to the sides.<br/> • The queen is the most powerful piece. She can move in any one straight direction - forward, backward, sideways, or diagonally - as far as possible as long as she does not move through any of her own pieces.<br/> • The king is the most important piece, but is one of the weakest. The king can only move one square in any direction - up, down, to the sides, and diagonally. The king may never move himself into check (where he could be captured).<br/> <br/> To Move your pieces please enter the starting coordinates of your piece followed by the end coordinates. Have Fun! </html>");
        helpPage.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 450, 410));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        helpPage.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(helpPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 520, 480));

        gameBoard.setLayout(new java.awt.GridLayout(8, 8));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Rook-Black.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton1.setBorderPainted(false);
        jButton1.setHideActionText(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gameBoard.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Knight-Black.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton2.setBorderPainted(false);
        jButton2.setHideActionText(true);
        gameBoard.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Bishop-Black.png"))); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton3.setBorderPainted(false);
        jButton3.setHideActionText(true);
        gameBoard.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Queen-Black.png"))); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton4.setBorderPainted(false);
        jButton4.setHideActionText(true);
        gameBoard.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/King-Black.png"))); // NOI18N
        jButton5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton5.setBorderPainted(false);
        jButton5.setHideActionText(true);
        gameBoard.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Bishop-Black.png"))); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton6.setBorderPainted(false);
        jButton6.setHideActionText(true);
        gameBoard.add(jButton6);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Knight-Black.png"))); // NOI18N
        jButton7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton7.setBorderPainted(false);
        jButton7.setHideActionText(true);
        gameBoard.add(jButton7);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Rook-Black.png"))); // NOI18N
        jButton8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton8.setBorderPainted(false);
        jButton8.setHideActionText(true);
        gameBoard.add(jButton8);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Pawn-Black.png"))); // NOI18N
        jButton9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton9.setBorderPainted(false);
        jButton9.setHideActionText(true);
        gameBoard.add(jButton9);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Pawn-Black.png"))); // NOI18N
        jButton10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton10.setBorderPainted(false);
        jButton10.setHideActionText(true);
        gameBoard.add(jButton10);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Pawn-Black.png"))); // NOI18N
        jButton11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton11.setBorderPainted(false);
        jButton11.setHideActionText(true);
        gameBoard.add(jButton11);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Pawn-Black.png"))); // NOI18N
        jButton12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton12.setBorderPainted(false);
        jButton12.setHideActionText(true);
        gameBoard.add(jButton12);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Pawn-Black.png"))); // NOI18N
        jButton13.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton13.setBorderPainted(false);
        jButton13.setHideActionText(true);
        gameBoard.add(jButton13);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Pawn-Black.png"))); // NOI18N
        jButton14.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton14.setBorderPainted(false);
        jButton14.setHideActionText(true);
        gameBoard.add(jButton14);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Pawn-Black.png"))); // NOI18N
        jButton15.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton15.setBorderPainted(false);
        jButton15.setHideActionText(true);
        gameBoard.add(jButton15);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Pawn-Black.png"))); // NOI18N
        jButton16.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton16.setBorderPainted(false);
        jButton16.setHideActionText(true);
        gameBoard.add(jButton16);

        jButton17.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton17.setBorderPainted(false);
        jButton17.setHideActionText(true);
        gameBoard.add(jButton17);

        jButton18.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton18.setBorderPainted(false);
        jButton18.setHideActionText(true);
        gameBoard.add(jButton18);

        jButton19.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton19.setBorderPainted(false);
        jButton19.setHideActionText(true);
        gameBoard.add(jButton19);

        jButton20.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton20.setBorderPainted(false);
        jButton20.setHideActionText(true);
        gameBoard.add(jButton20);

        jButton21.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton21.setBorderPainted(false);
        jButton21.setHideActionText(true);
        gameBoard.add(jButton21);

        jButton22.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton22.setBorderPainted(false);
        jButton22.setHideActionText(true);
        gameBoard.add(jButton22);

        jButton23.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton23.setBorderPainted(false);
        jButton23.setHideActionText(true);
        gameBoard.add(jButton23);

        jButton24.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton24.setBorderPainted(false);
        jButton24.setHideActionText(true);
        gameBoard.add(jButton24);

        jButton25.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton25.setBorderPainted(false);
        jButton25.setHideActionText(true);
        gameBoard.add(jButton25);

        jButton26.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton26.setBorderPainted(false);
        jButton26.setHideActionText(true);
        gameBoard.add(jButton26);

        jButton27.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton27.setBorderPainted(false);
        jButton27.setHideActionText(true);
        gameBoard.add(jButton27);

        jButton29.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton29.setBorderPainted(false);
        jButton29.setHideActionText(true);
        gameBoard.add(jButton29);

        jButton28.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton28.setBorderPainted(false);
        jButton28.setHideActionText(true);
        gameBoard.add(jButton28);

        jButton30.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton30.setBorderPainted(false);
        jButton30.setHideActionText(true);
        gameBoard.add(jButton30);

        jButton31.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton31.setBorderPainted(false);
        jButton31.setHideActionText(true);
        gameBoard.add(jButton31);

        jButton32.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton32.setBorderPainted(false);
        jButton32.setHideActionText(true);
        gameBoard.add(jButton32);

        jButton33.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton33.setBorderPainted(false);
        jButton33.setHideActionText(true);
        gameBoard.add(jButton33);

        jButton35.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton35.setBorderPainted(false);
        jButton35.setHideActionText(true);
        gameBoard.add(jButton35);

        jButton36.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton36.setBorderPainted(false);
        jButton36.setHideActionText(true);
        gameBoard.add(jButton36);

        jButton37.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton37.setBorderPainted(false);
        jButton37.setHideActionText(true);
        gameBoard.add(jButton37);

        jButton38.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton38.setBorderPainted(false);
        jButton38.setHideActionText(true);
        gameBoard.add(jButton38);

        jButton39.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton39.setBorderPainted(false);
        jButton39.setHideActionText(true);
        gameBoard.add(jButton39);

        jButton40.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton40.setBorderPainted(false);
        jButton40.setHideActionText(true);
        gameBoard.add(jButton40);

        jButton41.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton41.setBorderPainted(false);
        jButton41.setHideActionText(true);
        gameBoard.add(jButton41);

        jButton34.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton34.setBorderPainted(false);
        jButton34.setHideActionText(true);
        gameBoard.add(jButton34);

        jButton42.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton42.setBorderPainted(false);
        jButton42.setHideActionText(true);
        gameBoard.add(jButton42);

        jButton43.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton43.setBorderPainted(false);
        jButton43.setHideActionText(true);
        gameBoard.add(jButton43);

        jButton44.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton44.setBorderPainted(false);
        jButton44.setHideActionText(true);
        gameBoard.add(jButton44);

        jButton45.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton45.setBorderPainted(false);
        jButton45.setHideActionText(true);
        gameBoard.add(jButton45);

        jButton46.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton46.setBorderPainted(false);
        jButton46.setHideActionText(true);
        gameBoard.add(jButton46);

        jButton47.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton47.setBorderPainted(false);
        jButton47.setHideActionText(true);
        gameBoard.add(jButton47);

        jButton48.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton48.setBorderPainted(false);
        jButton48.setHideActionText(true);
        gameBoard.add(jButton48);

        jButton49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Pawn-White.png"))); // NOI18N
        jButton49.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton49.setBorderPainted(false);
        jButton49.setHideActionText(true);
        gameBoard.add(jButton49);

        jButton50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Pawn-White.png"))); // NOI18N
        jButton50.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton50.setBorderPainted(false);
        jButton50.setHideActionText(true);
        gameBoard.add(jButton50);

        jButton51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Pawn-White.png"))); // NOI18N
        jButton51.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton51.setBorderPainted(false);
        jButton51.setHideActionText(true);
        gameBoard.add(jButton51);

        jButton52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Pawn-White.png"))); // NOI18N
        jButton52.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton52.setBorderPainted(false);
        jButton52.setHideActionText(true);
        gameBoard.add(jButton52);

        jButton53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Pawn-White.png"))); // NOI18N
        jButton53.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton53.setBorderPainted(false);
        jButton53.setHideActionText(true);
        gameBoard.add(jButton53);

        jButton54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Pawn-White.png"))); // NOI18N
        jButton54.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton54.setBorderPainted(false);
        jButton54.setHideActionText(true);
        gameBoard.add(jButton54);

        jButton55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Pawn-White.png"))); // NOI18N
        jButton55.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton55.setBorderPainted(false);
        jButton55.setHideActionText(true);
        gameBoard.add(jButton55);

        jButton56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Pawn-White.png"))); // NOI18N
        jButton56.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton56.setBorderPainted(false);
        jButton56.setHideActionText(true);
        gameBoard.add(jButton56);

        jButton57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Rook-White.png"))); // NOI18N
        jButton57.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton57.setBorderPainted(false);
        jButton57.setHideActionText(true);
        gameBoard.add(jButton57);

        jButton58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Knight-White.png"))); // NOI18N
        jButton58.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton58.setBorderPainted(false);
        jButton58.setHideActionText(true);
        gameBoard.add(jButton58);

        jButton59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Bishop-White.png"))); // NOI18N
        jButton59.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton59.setBorderPainted(false);
        jButton59.setHideActionText(true);
        gameBoard.add(jButton59);

        jButton60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Queen-White.png"))); // NOI18N
        jButton60.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton60.setBorderPainted(false);
        jButton60.setHideActionText(true);
        gameBoard.add(jButton60);

        jButton61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/King-White.png"))); // NOI18N
        jButton61.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton61.setBorderPainted(false);
        jButton61.setHideActionText(true);
        gameBoard.add(jButton61);

        jButton62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Bishop-White.png"))); // NOI18N
        jButton62.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton62.setBorderPainted(false);
        jButton62.setHideActionText(true);
        gameBoard.add(jButton62);

        jButton63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Knight-White.png"))); // NOI18N
        jButton63.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton63.setBorderPainted(false);
        jButton63.setHideActionText(true);
        gameBoard.add(jButton63);

        jButton64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/Rook-White.png"))); // NOI18N
        jButton64.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton64.setBorderPainted(false);
        jButton64.setHideActionText(true);
        gameBoard.add(jButton64);

        getContentPane().add(gameBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 480));

        overlay.setBackground(new java.awt.Color(0, 0, 0));
        overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        overlay.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 740));

        getContentPane().add(overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -60, 540, 540));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wallpaper.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-350, -90, 830, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2ActionPerformed
        
    }//GEN-LAST:event_player2ActionPerformed

    private void player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1ActionPerformed
        
    }//GEN-LAST:event_player1ActionPerformed

    private void helpIsSelected(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_helpIsSelected
        if(help.isSelected()) {
            helpPage.setVisible(true);
        }
        else {
            helpPage.setVisible(false);
        }
    }//GEN-LAST:event_helpIsSelected

    private void startPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startPerformed
        if(evt.getSource() == start) {
            helpPage.setVisible(false);
            player1Name = player1.getText();
            player2Name = player2.getText();
            gameBoard.setVisible(true);
            sidePanel.setSelectedIndex(1);
            playerBlack.setText(player1Name + " - BLACK");
            playerWhite.setText(player2Name + " - WHITE");
            turnLabel.setText(" BLACK make your move...");
        }
    }//GEN-LAST:event_startPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JButton button = (JButton) evt.getSource();
        String name = button.getIcon().toString();
        System.out.println(name + "was selected");
    }//GEN-LAST:event_jButton1ActionPerformed

    
//----------------------------------------------------------------------------------------------------------------------------------------    
//----------------------------------------------------------------------------------------------------------------------------------------
//----------------------------------------------------------------------------------------------------------------------------------------    
//----------------------------------------------------------------------------------------------------------------------------------------        
    
    //GAME LOGIC
   
    
    
    
    
    
    
    
    
    
    
    
    
//----------------------------------------------------------------------------------------------------------------------------------------    
//----------------------------------------------------------------------------------------------------------------------------------------    
//----------------------------------------------------------------------------------------------------------------------------------------    
//----------------------------------------------------------------------------------------------------------------------------------------    

    
    // MAIN AND VARIABLES
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIChess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIChess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIChess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIChess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIChess().setVisible(true);
            }
        });
    }

    private String player1Name;
    private String player2Name;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JPanel gameBoard;
    private javax.swing.JToggleButton help;
    private javax.swing.JPanel helpPage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JPanel overlay;
    private javax.swing.JTextField player1;
    private javax.swing.JLabel player1Label;
    private javax.swing.JTextField player2;
    private javax.swing.JLabel player2Label;
    private javax.swing.JLabel playerBlack;
    private javax.swing.JPanel playerScores;
    private javax.swing.JLabel playerWhite;
    private javax.swing.JTabbedPane sidePanel;
    private javax.swing.JButton start;
    private javax.swing.JPanel startingPage;
    private javax.swing.JLabel turnLabel;
    // End of variables declaration//GEN-END:variables
}
